---
# This playbook prepares a basic CentOS environment for hadoop cluster

- name: Shutdown firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Disable SELinux
  selinux:
    state: disabled

- name: Change hosts name
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: "{{ item.ip }} {{ item.name }} {{ item.short_name }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.short_name }}"
  loop:
    - { ip: 192.168.33.101, name: node01.bigdata.com, short_name: node01 }
    - { ip: 192.168.33.102, name: node02.bigdata.com, short_name: node02 }
    - { ip: 192.168.33.103, name: node03.bigdata.com, short_name: node03 }

- name: Ensure ntpd installed
  yum:
    name: ntp
    state: installed

- name: Sync Clock through Internet
  cron:
    name: sync with ntp every minute
    minute: "*/1"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/sbin/ntpdate ntp4.aliyun.com"

- name: Ensure 'hadoop' group exists
  group:
    name: hadoop
    state: present

- name: Add the user 'hadoop'
  user:
    name: hadoop
    # ansible all -i localhost, -m debug -a "msg={{ '123456' | password_hash('sha512', 'mysecretsalt') }}"
    password: $6$mysecretsalt$ZB9R8AirQYAXhtfhOo2qdJz52FyNI6v3L6Uc3KNRP.arBKIYpcuEyQewT5qBAHoyQFwHkW6Z551Ql.cZ53GeY0
    group: hadoop
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/hadoop/.ssh/id_rsa
    ssh_key_passphrase: ""
    ssh_key_type: "rsa"

- name: Make user 'hadoop' sudoer
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^hadoop'
    line: 'hadoop ALL=(ALL) NOPASSWD: ALL'

- name: Create /bigdata/soft and /bigdata/install
  file:
    path: "{{ item }}"
    state: directory
    owner: hadoop
    group: hadoop
    recurse: yes
  loop:
    - "/bigdata/soft" 
    - "/bigdata/install" 

- name: Turn SSH password authentication on
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication yes"

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Ensure sshpass installed
  yum:
    name: sshpass
    state: installed

- name: Collect all public keys to node01
  become: yes
  become_user: hadoop
  command: sshpass -p "123456" ssh-copy-id -o StrictHostKeyChecking=no {{ item }}
  loop:
    - node01
    - node02
    - node03

- name: Turn SSH password authentication off
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"

- name: Turn SSH public key authentication on
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PubKeyAuthentication"
    line: "PubKeyAuthentication yes"

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Copy jdk tarball to /bigdata/soft
  copy:
    src: ../../../tars/jdk-8u141-linux-x64.tar.gz
    dest: /bigdata/soft
    owner: hadoop
    group: hadoop

- name: Extract JDK to /bigdata/install
  unarchive:
    src: /bigdata/soft/jdk-8u141-linux-x64.tar.gz
    remote_src: yes
    dest: /bigdata/install
    owner: hadoop
    group: hadoop

- name: Configure JDK environment
  blockinfile:
    path: /etc/profile
    block: |
      export JAVA_HOME=/bigdata/install/jdk1.8.0_141
      export PATH=$PATH:$JAVA_HOME/bin

- name: Reboot all machines
  reboot:


  